"""Alterando coluna para image_filenames

Revision ID: d27c5cb0c9f5
Revises: 
Create Date: 2025-05-05 21:39:11.662165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27c5cb0c9f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galeria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filenames', sa.String(length=500), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galeria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image_filenames')

    # ### end Alembic commands ###
