"""Criação ou alteração de campos

Revision ID: d33dd6b94687
Revises: d27c5cb0c9f5
Create Date: 2025-05-06 20:39:30.598906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33dd6b94687'
down_revision = 'd27c5cb0c9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galeria', schema=None) as batch_op:
        batch_op.alter_column('image_filenames',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galeria', schema=None) as batch_op:
        batch_op.alter_column('image_filenames',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
